// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML.Data;

namespace CarRecommendationSystemML.Model
{
    public class ModelInput
    {
        [ColumnName("car_id"), LoadColumn(0)]
        public float Car_id { get; set; }


        [ColumnName("name"), LoadColumn(1)]
        public string Name { get; set; }


        [ColumnName("year"), LoadColumn(2)]
        public float Year { get; set; }


        [ColumnName("price"), LoadColumn(3)]
        public float Price { get; set; }


        [ColumnName("overall_score"), LoadColumn(4)]
        public float Overall_score { get; set; }


        [ColumnName("driving_score"), LoadColumn(5)]
        public float Driving_score { get; set; }


        [ColumnName("comfort_score"), LoadColumn(6)]
        public float Comfort_score { get; set; }


        [ColumnName("interior_score"), LoadColumn(7)]
        public float Interior_score { get; set; }


        [ColumnName("tech_score"), LoadColumn(8)]
        public float Tech_score { get; set; }


        [ColumnName("storage_score"), LoadColumn(9)]
        public float Storage_score { get; set; }


        [ColumnName("economical_score"), LoadColumn(10)]
        public float Economical_score { get; set; }


        [ColumnName("good_value_score"), LoadColumn(11)]
        public float Good_value_score { get; set; }


        [ColumnName("litres_on_100km"), LoadColumn(12)]
        public float Litres_on_100km { get; set; }


        [ColumnName("seats"), LoadColumn(13)]
        public float Seats { get; set; }


        [ColumnName("transmission"), LoadColumn(14)]
        public string Transmission { get; set; }


        [ColumnName("horsepower"), LoadColumn(15)]
        public float Horsepower { get; set; }


        [ColumnName("fuel"), LoadColumn(16)]
        public string Fuel { get; set; }
    }
}
